apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx-source
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/your-username/your-repo
  ref:
    tag: "v1.0.0" # Flux will only deploy code from this specific Git tag
