apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
  interval: 1h
