apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/nginx/base
patches:
  - target:
      kind: HelmRelease
      name: nginx-poc
    patch: |-
      - op: replace
        path: /spec/values/replicaCount
        value: 3  # Overriding the base value for Production
