apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nginx-release.yaml
patches:
  - target:
      kind: Deployment
      name: .*
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2 # Override replicas to 2 for this specific cluster
