apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway # This connects to the "Hardware" you installed
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
      - "*"
    tls:
      mode: SIMPLE # Can be SIMPLE or MUTUAL depending on your architecture
      credentialName: nginx-gateway-tls # This is the secret name Cert-Manager will generate
---

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-egress
  namespace: default
spec:
  hosts:
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtualservice
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway
  http:
  - route:
    - destination:
        host: nginx-poc-svc # The name of your K8s service
        port:
          number: 80
